/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocumentacaoRouteImport } from './routes/documentacao'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVendedorRouteImport } from './routes/_authenticated/vendedor'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTransportadorasRouteImport } from './routes/_authenticated/transportadoras'
import { Route as AuthenticatedRodonavesRouteImport } from './routes/_authenticated/rodonaves'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRastreamentoRouteImport } from './routes/_authenticated/rastreamento'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedCotacaoRouteImport } from './routes/_authenticated/cotacao'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCidadesRouteImport } from './routes/_authenticated/cidades'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated/pedidos.$id'

const DocumentacaoRoute = DocumentacaoRouteImport.update({
  id: '/documentacao',
  path: '/documentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendedorRoute = AuthenticatedVendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransportadorasRoute =
  AuthenticatedTransportadorasRouteImport.update({
    id: '/transportadoras',
    path: '/transportadoras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRodonavesRoute = AuthenticatedRodonavesRouteImport.update({
  id: '/rodonaves',
  path: '/rodonaves',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRastreamentoRoute =
  AuthenticatedRastreamentoRouteImport.update({
    id: '/rastreamento',
    path: '/rastreamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCotacaoRoute = AuthenticatedCotacaoRouteImport.update({
  id: '/cotacao',
  path: '/cotacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCidadesRoute = AuthenticatedCidadesRouteImport.update({
  id: '/cidades',
  path: '/cidades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPedidosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/documentacao': typeof DocumentacaoRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/cidades': typeof AuthenticatedCidadesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cotacao': typeof AuthenticatedCotacaoRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/rastreamento': typeof AuthenticatedRastreamentoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/rodonaves': typeof AuthenticatedRodonavesRoute
  '/transportadoras': typeof AuthenticatedTransportadorasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendedor': typeof AuthenticatedVendedorRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
}
export interface FileRoutesByTo {
  '/documentacao': typeof DocumentacaoRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/cidades': typeof AuthenticatedCidadesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cotacao': typeof AuthenticatedCotacaoRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/rastreamento': typeof AuthenticatedRastreamentoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/rodonaves': typeof AuthenticatedRodonavesRoute
  '/transportadoras': typeof AuthenticatedTransportadorasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendedor': typeof AuthenticatedVendedorRoute
  '/': typeof AuthenticatedIndexRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/documentacao': typeof DocumentacaoRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/cidades': typeof AuthenticatedCidadesRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/cotacao': typeof AuthenticatedCotacaoRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/rastreamento': typeof AuthenticatedRastreamentoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/rodonaves': typeof AuthenticatedRodonavesRoute
  '/_authenticated/transportadoras': typeof AuthenticatedTransportadorasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/vendedor': typeof AuthenticatedVendedorRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/pedidos/$id': typeof AuthenticatedPedidosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documentacao'
    | '/auditoria'
    | '/cidades'
    | '/clientes'
    | '/configuracoes'
    | '/cotacao'
    | '/historico'
    | '/notificacoes'
    | '/pedidos'
    | '/perfil'
    | '/portal'
    | '/rastreamento'
    | '/relatorios'
    | '/rodonaves'
    | '/transportadoras'
    | '/usuarios'
    | '/vendedor'
    | '/pedidos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/documentacao'
    | '/auditoria'
    | '/cidades'
    | '/clientes'
    | '/configuracoes'
    | '/cotacao'
    | '/historico'
    | '/notificacoes'
    | '/pedidos'
    | '/perfil'
    | '/portal'
    | '/rastreamento'
    | '/relatorios'
    | '/rodonaves'
    | '/transportadoras'
    | '/usuarios'
    | '/vendedor'
    | '/'
    | '/pedidos/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/documentacao'
    | '/_authenticated/auditoria'
    | '/_authenticated/cidades'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/cotacao'
    | '/_authenticated/historico'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pedidos'
    | '/_authenticated/perfil'
    | '/_authenticated/portal'
    | '/_authenticated/rastreamento'
    | '/_authenticated/relatorios'
    | '/_authenticated/rodonaves'
    | '/_authenticated/transportadoras'
    | '/_authenticated/usuarios'
    | '/_authenticated/vendedor'
    | '/_authenticated/'
    | '/_authenticated/pedidos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DocumentacaoRoute: typeof DocumentacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/documentacao': {
      id: '/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof DocumentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendedor': {
      id: '/_authenticated/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof AuthenticatedVendedorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transportadoras': {
      id: '/_authenticated/transportadoras'
      path: '/transportadoras'
      fullPath: '/transportadoras'
      preLoaderRoute: typeof AuthenticatedTransportadorasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rodonaves': {
      id: '/_authenticated/rodonaves'
      path: '/rodonaves'
      fullPath: '/rodonaves'
      preLoaderRoute: typeof AuthenticatedRodonavesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rastreamento': {
      id: '/_authenticated/rastreamento'
      path: '/rastreamento'
      fullPath: '/rastreamento'
      preLoaderRoute: typeof AuthenticatedRastreamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotacao': {
      id: '/_authenticated/cotacao'
      path: '/cotacao'
      fullPath: '/cotacao'
      preLoaderRoute: typeof AuthenticatedCotacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cidades': {
      id: '/_authenticated/cidades'
      path: '/cidades'
      fullPath: '/cidades'
      preLoaderRoute: typeof AuthenticatedCidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/$id': {
      id: '/_authenticated/pedidos/$id'
      path: '/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedPedidosRoute
    }
  }
}

interface AuthenticatedPedidosRouteChildren {
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRoute
}

const AuthenticatedPedidosRouteChildren: AuthenticatedPedidosRouteChildren = {
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRoute,
}

const AuthenticatedPedidosRouteWithChildren =
  AuthenticatedPedidosRoute._addFileChildren(AuthenticatedPedidosRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCidadesRoute: typeof AuthenticatedCidadesRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCotacaoRoute: typeof AuthenticatedCotacaoRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedRastreamentoRoute: typeof AuthenticatedRastreamentoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedRodonavesRoute: typeof AuthenticatedRodonavesRoute
  AuthenticatedTransportadorasRoute: typeof AuthenticatedTransportadorasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVendedorRoute: typeof AuthenticatedVendedorRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCidadesRoute: AuthenticatedCidadesRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCotacaoRoute: AuthenticatedCotacaoRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedRastreamentoRoute: AuthenticatedRastreamentoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedRodonavesRoute: AuthenticatedRodonavesRoute,
  AuthenticatedTransportadorasRoute: AuthenticatedTransportadorasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVendedorRoute: AuthenticatedVendedorRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DocumentacaoRoute: DocumentacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
